import {
    StyleSheet,
    Platform,
    Dimensions
  } from 'react-native';
const {width,height} = Dimensions.get("window");
export default StyleSheet.create({
        window:{
        width:width,
        height:height
        },
        container:{
        flex:1,
        justifyContent:"center",
        alignItems:"center"
        },
        tabtitle:{
            fontSize:10
        },
        title:{
            fontSize:12,
            fontWeight:"bold",
            color:"black"
        },
        whitetxt:{
          color:"white"
        },
        subtitle:{
            fontSize:12,
            color:"#696969"
        },
        active:{color:"#e53834"},
        inactive:{color:"#000"},
        btn:{
          backgroundColor:"#e53834",
          padding:10,
          alignSelf:"center",
          flexDirection:"row",
          justifyContent:"center",
          alignItems:"center",
          borderRadius:20,
          marginHorizontal:2
        },
        tag:{
          flexDirection:"row",
          flexDirection:"row",
          justifyContent:"center",
          alignItems:"center",
          alignSelf:"center",
          borderRadius:20,
          padding:5,
          paddingHorizontal:10,
          borderColor:"#ee3124",
          borderWidth:0.5,
          marginHorizontal:2
        },
        card:{
          backgroundColor:"white",
          borderRadius:20,
          overflow:"hidden"
        },
        myalert:{
          padding:10,
          backgroundColor:'#ffe2e2',
          width:'95%',
          flexDirection:"row",
          margin:10
          },
          codewrp:{
            flexDirection:"row",
            alignItems:"center",
            justifyContent:"center",
            
         },
         codeInner:{
             borderColor:'#ccc',
             borderRadius: 5,
             borderWidth: 1,
             flex:1,
             minHeight:40,
             marginHorizontal:2,
             textAlign:"center",
             alignItems:"center",
            justifyContent:"center",
             fontSize:30,
             backgroundColor:"white"
         },
         btninactive:{
          backgroundColor:"#e9e3e3",
          padding:10,
          alignSelf:"center",
          flexDirection:"row",
          justifyContent:"center",
          alignItems:"center",
          borderRadius:20,
          marginHorizontal:2,
          elevation:5
        },
        inputwrp:{
          flexDirection:"row",
          alignItems:"center",
          justifyContent:"center",
          backgroundColor:"#e9e3e3",
          width:"100%",
          borderRadius:60,
          height:40,
          elevation:5,
          overflow:"hidden"
       },
       modalback:{
        flex:1,
        backgroundColor:"rgba(0,0,0,0.7)",
        alignItems:"center",
        justifyContent:"center",
        padding:20
      },
      modalInner:{
        flex:1,
        margin:10,
        alignItems:'center',
        justifyContent:'center',
        },
        regInput:{
         margin:10,
         backgroundColor:"#e9e3e3",
         borderRadius:10 
        },
        codewrp:{
          flexDirection:"row",
          alignItems:"center",
          justifyContent:"center",
       },
       codeInner:{
           borderColor:'#ccc',
           flex:1,
           minHeight:50,
           marginHorizontal:5,
           textAlign:"center",
           alignItems:"center",
           justifyContent:"center",
           fontSize:20,
           backgroundColor:"#f3f4fd"
       }
    })